additional_commands:
  domain: "^domain(\\(.+\\))?:"
  application: "^application(\\(.+\\))?:"
  infrastructure: "^infrastructure(\\(.+\\))?:"
  api: "^api(\\(.+\\))?:"
  entity: "^entity(\\(.+\\))?:"
  repository: "^repository(\\(.+\\))?:"
  service: "^service(\\(.+\\))?:"
  controller: "^controller(\\(.+\\))?:"
  config: "^config(\\(.+\\))?:"
  csv: "^csv(\\(.+\\))?:"
  h2: "^h2(\\(.+\\))?:"
  jpa: "^jpa(\\(.+\\))?:"
  maven: "^maven(\\(.+\\))?:"
  spring: "^spring(\\(.+\\))?:"

additional_emojis:
  domain: " ğŸ—ï¸ "
  application: " ğŸ“‹ "
  infrastructure: " ğŸ”§ "
  api: " ğŸŒ "
  entity: " ğŸ“¦ "
  repository: " ğŸ—ƒï¸ "
  service: " âš™ï¸ "
  controller: " ğŸ® "
  config: " âš™ï¸ "
  csv: " ğŸ“„ "
  h2: " ğŸ’¾ "
  jpa: " ğŸ—„ï¸ "
  maven: " ğŸ“¦ "
  spring: " ğŸƒ "
